backend:
  name: github
  repo: Humanists-of-Miami/Humanists-of-Miami.github.io
  branch: master
media_folder: "assets/img/uploads"
site_url: https://Humanists-of-Miami.github.io
logo_url: https://Humanists-of-Miami.github.io/assets/images/miami/logo.svg
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    preview_path: "posts/{{year}}/{{month}}/{{day}}/{{slug}}"
    extension: "mokkf"
    format: "yaml-frontmatter"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "posts"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/{{ page.data.collection }}/{{ page.date.year }}/{{ page.date.month }}/{{ page.date.day }}/{{ page.name }}/index.html"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: "author", widget: "select", options: ["Emil", "Evan", "Nishan", "Ais", "Catarina", "Connor", "Club"], required: true}
      - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", format: "YYYY-MM-DDTHH:mm:ss+00:00", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: true, allow_add: true, default: [""]}
      - {label: "Markdown", name: "markdown", widget: "boolean", default: true, required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{title}}.html"
    extension: "mokkf"
    format: "yaml-frontmatter"
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Collection", name: "collection", widget: "hidden", default: "pages"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "none"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Em", "Evan", "Both"]}
      - {label: "Markdown", name: "markdown", widget: "boolean", default: "true"}
      - {label: "Body", name: "body", widget: "markdown"}